services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      APP_KEY: base64:AHwGpMH1t1Igm6GXlNmRWVto7WGjeLPzoeIsADyfGzc=
      APP_DEBUG: "true"
      APP_URL: https://blogapi-23wq.onrender.com/
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: blog_api
      DB_USERNAME: postgres
      DB_PASSWORD: 08024983733Qq
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 08024983733Qq
      POSTGRES_DB: blog_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
